import { PatientData } from './types';

// 22 Cities/Counties with unique passwords
export const RELIEF_CENTERS = [
  { name: "목포시 치매안심센터", password: "1001" },
  { name: "여수시 치매안심센터", password: "2002" },
  { name: "순천시 치매안심센터", password: "3003" },
  { name: "나주시 치매안심센터", password: "4004" },
  { name: "광양시 치매안심센터", password: "5005" },
  { name: "담양군 치매안심센터", password: "6006" },
  { name: "곡성군 치매안심센터", password: "7007" },
  { name: "구례군 치매안심센터", password: "8008" },
  { name: "고흥군 치매안심센터", password: "9009" },
  { name: "보성군 치매안심센터", password: "1010" },
  { name: "화순군 치매안심센터", password: "1111" },
  { name: "장흥군 치매안심센터", password: "1212" },
  { name: "강진군 치매안심센터", password: "1313" },
  { name: "해남군 치매안심센터", password: "1414" },
  { name: "영암군 치매안심센터", password: "1515" },
  { name: "무안군 치매안심센터", password: "1616" },
  { name: "함평군 치매안심센터", password: "1717" },
  { name: "영광군 치매안심센터", password: "1818" },
  { name: "장성군 치매안심센터", password: "1919" },
  { name: "완도군 치매안심센터", password: "2020" },
  { name: "진도군 치매안심센터", password: "2121" },
  { name: "신안군 치매안심센터", password: "2222" }
];

// Dropdown Options
export const DEVICE_STATUS_OPTIONS = ["정상", "수리중", "분실", "해지"];
export const GUARDIAN_RELATIONSHIPS = ["배우자", "딸", "아들", "손자", "손녀", "사위", "며느리", "형제", "부", "모", "조부", "조모", "친인척", "성년후견인", "친구", "이웃", "간병인", "기타"];
// Moved "병원∙시설 입소" to the end as requested
export const NON_USAGE_REASONS = ["고장", "분실", "사망", "보호자의 관리 소홀", "사용효과 미비", "착용의 불편감", "기타", "병원∙시설 입소"];

export const INITIAL_MOCK_DATA: PatientData[] = [
  {
    id: '1',
    sequenceNumber: 1,
    centerName: '여수시 치매안심센터',
    serialNumber: '1002034',
    deviceStatus: '정상',
    applicationDate: '2023-10-15',
    openingDate: '2023-10-16',
    expirationDate: '2025-10-15',
    name: '김철수',
    gender: '남',
    birthDate: '1945-05-20',
    age: 78,
    address: '전라남도 여수시 시청로 1',
    detailAddress: '101동 202호',
    contact: '010-1234-5678',
    diagnosis: '치매',
    missingExperience: '유',
    missingCount: 1,
    guardianName: '김영희',
    guardianRelationship: '딸',
    guardianGender: '여',
    guardianBirthDate: '1975-01-01',
    guardianContact1: '010-9999-8888',
    usageStatus: '사용중'
  },
  {
    id: '2',
    sequenceNumber: 2,
    centerName: '순천시 치매안심센터',
    serialNumber: '2005001',
    deviceStatus: '정상',
    applicationDate: '2023-10-18',
    openingDate: '2023-10-19',
    expirationDate: '2025-10-18',
    name: '이순자',
    gender: '여',
    birthDate: '1941-08-15',
    age: 82,
    address: '전라남도 순천시 중앙로 5',
    detailAddress: '주택 1층',
    contact: '010-9876-5432',
    diagnosis: '치매',
    missingExperience: '무',
    missingCount: 0,
    guardianName: '박철수',
    guardianRelationship: '배우자',
    guardianGender: '남',
    guardianBirthDate: '1940-02-02',
    guardianContact1: '010-7777-6666',
    usageStatus: '사용중'
  },
   {
    id: '3',
    sequenceNumber: 3,
    centerName: '목포시 치매안심센터',
    serialNumber: '3009988',
    deviceStatus: '해지',
    applicationDate: '2023-01-10',
    openingDate: '2023-01-12',
    expirationDate: '2024-01-12',
    name: '최영수',
    gender: '남',
    birthDate: '1950-12-25',
    age: 73,
    address: '전라남도 목포시 해안로 10',
    detailAddress: '',
    contact: '010-5555-4444',
    diagnosis: '경도인지장애',
    missingExperience: '무',
    missingCount: 0,
    guardianName: '최민수',
    guardianRelationship: '아들',
    guardianGender: '남',
    guardianBirthDate: '1980-05-05',
    guardianContact1: '010-1111-2222',
    usageStatus: '미사용중',
    nonUsageReason: '착용의 불편감',
    nonUsageAlternative: '없음',
    patientRequest: '사용 방법 교육',
    nonUsageEncouragement: 'O',
    nonUsagePlan: '다음 달 방문하여 재교육 예정'
  }
];